name: libre_gcnn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - hyperopt
  - seaborn
  - keras
  - matplotlib==3.1.0
  - scikit-learn
  - deepchem==2.3.0
  - tensorflow-gpu=1.14
  - plotly


